### ISSUE TITLE
Redirect to /home if user is loggedin

### ISSUE THREAD

**Issue by AntonioK180** [AntonioK180/react-trello-board#27]
Hey @StoyanTinchev can we make a redirect to /home if the user is already loggedin?

**Comment by StoyanTinchev** [comment]
Hey @AntonioK180 there is such functionality already

**Comment by AntonioK180** [comment]
Well, it doesn't work. We may sync this later on a call, OK?

**Comment by AntonioK180** [comment]
Problem was fixed.
